### ISSUE TITLE
[Q] obtain signals in Picode format

### ISSUE THREAD

**Issue by eadmaster** [latchdevel/raspicode#1]
which method do you recommend to obtain rf signals in Picode format?

I am able to read signals using [this script](https://github.com/milaq/rpi-rf/blob/master/scripts/rpi-rf_receive) , but the format is a bit different:

````
rpi-rf_send  -p 175 -t 1 4478268
````

(i'd like to clone signals sent from an outlet remote)

**Comment by latchdevel** [comment]
**rpi-rf** uses the [rc-switch](https://github.com/sui77/rc-switch) format, which is very limited, although for simple uses it can be useful.

Direct capture of codes in picode format is implemented for microcontrollers like as Arduino or similar [pilight-usb-nano](https://github.com/latchdevel/pilight-usb-nano)

However, if capturing with rpi-rf is enough for you, it will be easy to add a translation option between formats, perhaps in the python package [pyPicode](https://github.com/latchdevel/pyPiCode)

Let me think about it.

Best regards.
Jorge.

**Comment by latchdevel** [comment]
@eadmaster, 

For an early test, the command `rpi-rf_send -p 175 -t 1 4478268` generates this pulse train, which can be easily converted to picode format with the [picoder](https://github.com/latchdevel/picoder) tool.

```
picoder convert -t "175,525,525,175,175,525,175,525,175,525,525,175,175,525,175,525,175,525,525,175,175,525,525,175,175,525,525,175,175,525,525,175,175,525,175,525,525,175,525,175,525,175,525,175,175,525,175,525,175,5425"
c:01100101011001010110011001100110010110101010010102;p:175,525,5425@
```

This code is very similar to the "**clarus_switch**" protocol, since by simply increasing the synchronization pulse a little it can be decoded:

`picoder decode -s "c:01100101011001010110011001100110010110101010010102;p:175,525,5500@"`                                                                                                                                  
```json
{
  "protocols": [{
    "clarus_switch": {
      "id": "A3",
      "unit": 20,
      "state": "off"
    }
  }]
}
```

And this way it is very easy to generate similar codes, for example, to turn on the same switch it would be:

```
picoder encode -f '{"clarus_switch":{"id":"A3","unit":20,"on":1}}' 
c:01100101011001010110011001100110010110100101101002;p:180,540,6120@
```

Try this picodes to see if we are on the right track.

Thanks.
Jorge.

**Comment by eadmaster** [comment]
thanks for your help, unfortunately i'm having some issues with the FS1000A transmitter currently, i am trying to figure out if i've got  a defective unit or not.
If i manage to get it working i'll update the issue.

**Comment by latchdevel** [comment]
The FS1000A transmitter is really bad, try to get another one with better quality, Aliexpress is ok for this:
- STX882 https://aliexpress.com/item/32916792997.html
- H34A https://aliexpress.com/item/1005006707094817.html

More info here: http://x311.blogspot.com/2017/10/comparison-of-cheap-rf-modules-with-ask.html

Good luck!

**Comment by eadmaster** [comment]
I also have a [CC1101 module that should be compatible](https://www.aliexpress.com/item/1005002074380868.html), so i am trying to use that instead before the next aliexpress order :-).

So far the module gets recognized by [this script](https://github.com/nahueldsanchez/pycc1101/blob/master/rx.py), but it is not reading the signals coming from my remote.

**Comment by latchdevel** [comment]
Using the CC1101 is easily possible with any Arduino.

[Pilight Arduino Nano CC1101](https://github.com/latchdevel/SmartRC-CC1101-Driver-Lib/tree/main/examples/Pilight%20Arduino%20Nano%20cc1101)

**Comment by latchdevel** [comment]
@eadmaster

If you still want to use RCSwitch to capture or generate RC codes, I have implemented a utility to encode and decode RC codes into pulse trains that can be easily converted to PICODE format.

[RCSwitch Common Library](https://github.com/latchdevel/rc-switch-lib)

Good luck!

**Comment by latchdevel** [comment]
Finally, I developed a Python module to wrap the **C++ RCSwitch Common Library** to easily translate RCSwitch codes to PiCode string format. 

[pyRCSwitch](https://github.com/latchdevel/pyRCSwitch)

This way you can translate the command you needed (`rpi-rf_send  -p 175 -t 1 4478268`) into picode format like this:

```python
>>> import pypicode as picode
>>> 
>>> from pyRCSwitch import RCSwitch
>>> mySwitch = RCSwitch()
>>> 
>>> mySwitch.setProtocol(1, 175)
>>> 
>>> picode.pulseTrainToString( mySwitch.send(4478268, 24) )
'c:01100101011001010110011001100110010110101010010102;p:175,525,5425@'
```
I hope I have been helpful.
Bests regards.

**Comment by eadmaster** [comment]
ok, i've managed to write [this sketch](https://github.com/latchdevel/SmartRC-CC1101-Driver-Lib/blob/main/examples/Pilight%20Arduino%20Nano%20cc1101/pilight-usb-nano-cc1101/pilight-usb-nano-cc1101.ino) to an ESP32. 

I am getting the "CC1101 SPI Connection Error". My CC1101 is wired like this:

- SCK -  GPIO14
- MISO - GPIO12
- MOSI - GPIO13
- GDO2 - GPIO4 (RX_PIN in the code)
- GDO0 - GPIO5 (TX_PIN in the code)

am i missing something?

EDIT: maybe some pins must be redefined in that script, i am able to get "CC1101 initialized" correctly [with this](https://github.com/mcore1976/cc1101-tool/blob/main/cc1101-tool-esp32.ino).

**Comment by eadmaster** [comment]
UPDATE: after adding these lines in the [setup() function](https://github.com/latchdevel/SmartRC-CC1101-Driver-Lib/blob/main/examples/Pilight%20Arduino%20Nano%20cc1101/pilight-usb-nano-cc1101/pilight-usb-nano-cc1101.ino#L123), now it seems to init the module correctly:

````
byte sck = 14;
byte miso = 12;
byte mosi = 13;
byte ss = 20;
int gdo0 = 5;
int gdo2 = 4; 

     ELECHOUSE_cc1101.setSpiPin(sck, miso, mosi, ss);
     ELECHOUSE_cc1101.setGDO(gdo0, gdo2);
    ELECHOUSE_cc1101.Init();
````

EDIT: nevermind, i've found i had the `SPI CS` not connected correctly.
